"""Add token_created_at to users

Revision ID: 43ea1ae4e122
Revises: d2f1b8e46210
Create Date: 2025-05-10 23:31:24.607855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ea1ae4e122'
down_revision = 'd2f1b8e46210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_created_at')

    # ### end Alembic commands ###
