"""Add all model about Milking

Revision ID: 4a2982c77ff6
Revises: 57dddd673e63
Create Date: 2025-05-12 23:56:20.077670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2982c77ff6'
down_revision = '57dddd673e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milk_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_number', sa.String(length=50), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('FRESH', 'EXPIRED', 'USED', name='milkstatus'), nullable=False),
    sa.Column('production_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_table('daily_milk_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('morning_volume', sa.Float(), nullable=False),
    sa.Column('afternoon_volume', sa.Float(), nullable=False),
    sa.Column('evening_volume', sa.Float(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=False),
    sa.Column('average_fat_content', sa.Float(), nullable=True),
    sa.Column('average_protein_content', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milking_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=False),
    sa.Column('milker_id', sa.Integer(), nullable=False),
    sa.Column('milk_batch_id', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('milking_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.ForeignKeyConstraint(['milk_batch_id'], ['milk_batches.id'], ),
    sa.ForeignKeyConstraint(['milker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milking_sessions')
    op.drop_table('daily_milk_summary')
    op.drop_table('milk_batches')
    # ### end Alembic commands ###
