"""Add name and birth columns to User model

Revision ID: 624f0569246b
Revises: 7cef9b9bcec6
Create Date: 2025-05-11 14:10:02.680049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624f0569246b'
down_revision = '7cef9b9bcec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birth')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
