"""perbaikan relasi user-cow dan struktur model

Revision ID: 7cef9b9bcec6
Revises: 43ea1ae4e122
Create Date: 2025-05-11 01:20:47.967165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cef9b9bcec6'
down_revision = '43ea1ae4e122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cow_association', schema=None) as batch_op:
        batch_op.drop_constraint('user_cow_association_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('user_cow_association_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cows', ['cow_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_cow_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_cow_association_ibfk_2', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_cow_association_ibfk_1', 'cows', ['cow_id'], ['id'])

    # ### end Alembic commands ###
