"""Modification daily_milk_summary

Revision ID: e4c92013448b
Revises: 4a2982c77ff6
Create Date: 2025-05-13 01:37:10.369229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4c92013448b'
down_revision = '4a2982c77ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_milk_summary', schema=None) as batch_op:
        batch_op.drop_column('average_protein_content')
        batch_op.drop_column('average_fat_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_milk_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_fat_content', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('average_protein_content', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
